# Generated by Django 5.0.6 on 2024-05-28 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_facil_api_rest', '0003_rename_day_hoursscheduling_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
