# Generated by Django 5.0.6 on 2024-05-28 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_facil_api_rest', '0004_remove_barber_updated_at_barbershop_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
