# Generated by Django 5.0.6 on 2025-01-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_facil_api_rest', '0005_barber_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='barber_shop',
            new_name='barberShop',
        ),
        migrations.RemoveField(
            model_name='hoursscheduling',
            name='Day',
        ),
        migrations.AlterModelTable(
            name='barber',
            table='corte_facil_api_rest_barber',
        ),
        migrations.AlterModelTable(
            name='barbershop',
            table='corte_facil_api_rest_barbershop',
        ),
        migrations.AlterModelTable(
            name='client',
            table='corte_facil_api_rest_client',
        ),
        migrations.AlterModelTable(
            name='scheduling',
            table='corte_facil_api_rest_scheduling',
        ),
        migrations.AlterModelTable(
            name='schedulinghistoric',
            table='corte_facil_api_rest_schedulinghistoric',
        ),
        migrations.AddField(
            model_name='hoursscheduling',
            name='day',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terça', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sábado', 'Sábado')], default='Today', max_length=20),
        ),
    ]
